# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='summary.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rsummary.proto\"*\n\x07\x45pisode\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0bperformance\x18\x02 \x01(\x02\"%\n\x07Summary\x12\x1a\n\x08\x65pisodes\x18\x01 \x03(\x0b\x32\x08.Episodeb\x06proto3')
)




_EPISODE = _descriptor.Descriptor(
  name='Episode',
  full_name='Episode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Episode.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='performance', full_name='Episode.performance', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=59,
)


_SUMMARY = _descriptor.Descriptor(
  name='Summary',
  full_name='Summary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='episodes', full_name='Summary.episodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=98,
)

_SUMMARY.fields_by_name['episodes'].message_type = _EPISODE
DESCRIPTOR.message_types_by_name['Episode'] = _EPISODE
DESCRIPTOR.message_types_by_name['Summary'] = _SUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Episode = _reflection.GeneratedProtocolMessageType('Episode', (_message.Message,), dict(
  DESCRIPTOR = _EPISODE,
  __module__ = 'summary_pb2'
  # @@protoc_insertion_point(class_scope:Episode)
  ))
_sym_db.RegisterMessage(Episode)

Summary = _reflection.GeneratedProtocolMessageType('Summary', (_message.Message,), dict(
  DESCRIPTOR = _SUMMARY,
  __module__ = 'summary_pb2'
  # @@protoc_insertion_point(class_scope:Summary)
  ))
_sym_db.RegisterMessage(Summary)


# @@protoc_insertion_point(module_scope)
